nodeLinker: node-modules
npmMinimalAgeGate: '3d'

npmPreapprovedPackages:
  - '@simpleclub-extended/*'

npmScopes:
  simpleclub-extended:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.pkg.github.com'
